name: QuickJS-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CMAKE_GENERATOR: Ninja
  CMAKE_GENERATOR_PLATFORM: x64

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Check format
        run: |
          git diff --exit-code --name-only --diff-filter=ACMRTUXB | grep -E '\.(c|h|cpp|hpp)$' | xargs clang-format -i
          git diff --exit-code

  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            choco install ninja
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get install ninja-build
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            brew install ninja
          fi
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G "${{ env.CMAKE_GENERATOR }}" -A "${{ env.CMAKE_GENERATOR_PLATFORM }}" ..
          cmake --build . --config Release
