name: QuickJS-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CMAKE_GENERATOR: Ninja

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Check format
        run: |
          clang-format -style=file -i src/*.{cpp,hpp}
          git diff --exit-code

  check_lint:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-tidy
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15 all
      - name: Check lint
        run: |
          clang-tidy --version
          clang-tidy src/*.cpp src/*.hpp -- -std=c++23

  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Set up GCC
        if: runner.os == 'Linux'
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Configure using CMake (!Windows)
        if: runner.os != 'Windows'
        env:
          CC: gcc-12
          CXX: g++-12
        run: |
          mkdir build
          cd build
          cmake -G "${{ env.CMAKE_GENERATOR }}" ..
      - name: Configure using CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cd build
          cmake -G "${{ env.CMAKE_GENERATOR }}" ..
      - name: Build
        run: |
          cmake --build . --config Release
