name: QuickJS-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CMAKE_GENERATOR: Ninja

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Check format
        run: |
          git diff --exit-code --name-only --diff-filter=ACMRTUXB | grep -E '\.(c|h|cpp|hpp)$' | xargs clang-format -i
          git diff --exit-code

  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G "${{ env.CMAKE_GENERATOR }}" ..
          cmake --build . --config Release
